/* =============================================================
   knowledgepacks-1.js  —  NDIS · Government
============================================================= */
'use strict';

const PACK_NDIS = {
  code: 'NDIS', icon: '🧩', tier: 1,
  description: 'Registered NDIS provider delivering funded supports to participants with disability. Regulated by the NDIS Quality and Safeguards Commission. Revenue via NDIS claims submitted through PRODA/myplace. Commercial viability driven by billable utilisation, plan utilisation, claim approval rates, and SIL occupancy.',
  signals: [
    'participant','ndis plan','support worker','sil','billable hours','proda',
    'support category','plan utilisation','schads','registered provider',
    'support coordination','plan manager','ndis','ndia','participant funding',
    'service agreement','ndis price','worker screening','rostering','timesheet claim',
    'supported independent living','capacity building','daily activities',
    'disability support','sda','early childhood','plan review','myplace',
  ],
  capabilities: [
    'Participant intake and onboarding',
    'Support plan management and goal tracking',
    'Service agreement creation and management',
    'Roster and scheduling management',
    'Timesheet capture and approval',
    'NDIS claim submission via PRODA',
    'Plan utilisation monitoring and alerts',
    'Support Coordination and plan management',
    'Incident and risk management',
    'Workforce compliance (Worker Screening, SCHADS)',
    'NDIS Commission audit readiness',
    'SIL house management and occupancy tracking',
    'Financial management against NDIS price limits',
  ],
  processes: [
    'Participant referral → assessment → intake → plan activation → service agreement',
    'Support plan review → goal alignment → service agreement amendment',
    'Roster creation → shift assignment → delivery confirmation → timesheet approval',
    'Approved timesheet → claim generation → PRODA submission → payment receipt',
    'Plan budget monitoring → utilisation alerts → plan review trigger',
    'Incident capture → severity classification → Commission notification → close-out',
    'Staff recruitment → Worker Screening → induction → compliance tracking',
    'SIL vacancy identification → participant matching → move-in → occupancy tracking',
  ],
  factTables: [
    {
      name: 'Fact_ServiceDelivery',
      grain: 'One row = one shift delivery per participant per support item',
      source: 'Rostering / CRM System',
      columns: [
        { name: 'ServiceDeliveryKey', type: 'INT',     desc: 'Surrogate key' },
        { name: 'ParticipantKey',     type: 'INT',     desc: 'FK → Dim_Participant' },
        { name: 'EmployeeKey',        type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'SupportItemKey',     type: 'INT',     desc: 'FK → Dim_SupportItem' },
        { name: 'LocationKey',        type: 'INT',     desc: 'FK → Dim_Location' },
        { name: 'DateKey',            type: 'INT',     desc: 'FK → Dim_Date (shift date — active)' },
        { name: 'PlannedHours',       type: 'DECIMAL', desc: 'Hours rostered' },
        { name: 'DeliveredHours',     type: 'DECIMAL', desc: 'Actual hours delivered' },
        { name: 'BillableHours',      type: 'DECIMAL', desc: 'Hours eligible for NDIS claim' },
        { name: 'NDISUnitRate',       type: 'DECIMAL', desc: 'NDIS PAPL rate applied' },
        { name: 'BillableAmount',     type: 'DECIMAL', desc: 'BillableHours × NDISUnitRate' },
        { name: 'IsWeekend',          type: 'BIT',     desc: 'Weekend rate flag (SCHADS)' },
        { name: 'IsPublicHoliday',    type: 'BIT',     desc: 'Public holiday rate flag (SCHADS)' },
        { name: 'IsGroupSession',     type: 'BIT',     desc: 'Group vs individual delivery' },
        { name: 'KMsTravelled',       type: 'DECIMAL', desc: 'Provider travel kilometres' },
        { name: 'ClaimStatus',        type: 'VARCHAR', desc: 'Draft/Submitted/Approved/Rejected/Paid' },
      ],
    },
    {
      name: 'Fact_Claims',
      grain: 'One row = one NDIS claim line submission',
      source: 'PRODA / Finance System',
      columns: [
        { name: 'ClaimKey',        type: 'INT',     desc: 'Surrogate key' },
        { name: 'ParticipantKey',  type: 'INT',     desc: 'FK → Dim_Participant' },
        { name: 'SupportItemKey',  type: 'INT',     desc: 'FK → Dim_SupportItem' },
        { name: 'DateKey',         type: 'INT',     desc: 'FK → Dim_Date (submission — active)' },
        { name: 'ServiceDateKey',  type: 'INT',     desc: 'FK → Dim_Date (service — inactive)' },
        { name: 'ClaimAmount',     type: 'DECIMAL', desc: 'Amount submitted' },
        { name: 'ApprovedAmount',  type: 'DECIMAL', desc: 'Amount approved' },
        { name: 'RejectedAmount',  type: 'DECIMAL', desc: 'Amount rejected' },
        { name: 'ClaimStatus',     type: 'VARCHAR', desc: 'Draft/Submitted/Approved/Rejected/Paid' },
        { name: 'RejectionReason', type: 'VARCHAR', desc: 'NDIA rejection reason' },
        { name: 'DaysToPayment',   type: 'INT',     desc: 'Submission to payment lag (days)' },
      ],
    },
    {
      name: 'Fact_PlanUtilisation',
      grain: 'One row = one participant × support category × snapshot date',
      source: 'Plan Management System',
      columns: [
        { name: 'UtilisationKey',      type: 'INT',     desc: 'Surrogate key' },
        { name: 'ParticipantKey',      type: 'INT',     desc: 'FK → Dim_Participant' },
        { name: 'SupportCategoryKey',  type: 'INT',     desc: 'FK → Dim_SupportCategory' },
        { name: 'DateKey',             type: 'INT',     desc: 'FK → Dim_Date (snapshot)' },
        { name: 'PlanBudget',          type: 'DECIMAL', desc: 'Total approved plan budget' },
        { name: 'AmountUtilised',      type: 'DECIMAL', desc: 'Cumulative spend to date' },
        { name: 'AmountRemaining',     type: 'DECIMAL', desc: 'Budget − Utilised' },
        { name: 'PlanEndDate',         type: 'DATE',    desc: 'Plan expiry date' },
        { name: 'DaysRemainingInPlan', type: 'INT',     desc: 'Days to plan end' },
      ],
    },
    {
      name: 'Fact_Roster',
      grain: 'One row = one employee × one roster day',
      source: 'Rostering System',
      columns: [
        { name: 'RosterKey',      type: 'INT',     desc: 'Surrogate key' },
        { name: 'EmployeeKey',    type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'ParticipantKey', type: 'INT',     desc: 'FK → Dim_Participant' },
        { name: 'LocationKey',    type: 'INT',     desc: 'FK → Dim_Location' },
        { name: 'DateKey',        type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'RosteredHours',  type: 'DECIMAL', desc: 'Hours planned' },
        { name: 'DeliveredHours', type: 'DECIMAL', desc: 'Hours worked' },
        { name: 'OvertimeHours',  type: 'DECIMAL', desc: 'Overtime hours' },
        { name: 'AbsentHours',    type: 'DECIMAL', desc: 'Rostered but absent' },
        { name: 'LeaveHours',     type: 'DECIMAL', desc: 'Approved leave hours' },
      ],
    },
    {
      name: 'Fact_Incidents',
      grain: 'One row = one incident event',
      source: 'Incident Management System',
      columns: [
        { name: 'IncidentKey',      type: 'INT',     desc: 'Surrogate key' },
        { name: 'ParticipantKey',   type: 'INT',     desc: 'FK → Dim_Participant' },
        { name: 'EmployeeKey',      type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'LocationKey',      type: 'INT',     desc: 'FK → Dim_Location' },
        { name: 'DateKey',          type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'IncidentType',     type: 'VARCHAR', desc: 'Behaviour of Concern / Medication Error / Injury / Near Miss / Other' },
        { name: 'Severity',         type: 'VARCHAR', desc: 'Low / Medium / High / Critical' },
        { name: 'IsNotifiable',     type: 'BIT',     desc: 'Reportable to NDIS Commission' },
        { name: 'DaysToResolution', type: 'INT',     desc: 'Days to close' },
        { name: 'IsOpen',           type: 'BIT',     desc: 'Still open flag' },
      ],
    },
  ],
  dimensions: [
    { name: 'Dim_Participant',     type: 'SCD2',     hierarchies: ['State → Region → Suburb → Participant'],                  key_columns: ['ParticipantKey','ParticipantID','FirstName','LastName','DateOfBirth','AgeGroup','Gender','PrimaryDisabilityType','PlanStartDate','PlanEndDate','PlanType','FundingType','IsActive','ReferralSource'] },
    { name: 'Dim_SupportItem',     type: 'Standard', hierarchies: ['SupportCategory → RegistrationGroup → SupportItem'],      key_columns: ['SupportItemKey','SupportItemNumber','SupportItemName','SupportCategoryKey','Unit','StandardRate','WeekendRate','PublicHolidayRate','EffectiveFrom','EffectiveTo'] },
    { name: 'Dim_SupportCategory', type: 'Standard', hierarchies: ['FundingPool → Category'],                                 key_columns: ['SupportCategoryKey','CategoryNumber','CategoryName','FundingPool'] },
    { name: 'Dim_Employee',        type: 'SCD2',     hierarchies: ['State → Region → Team → Employee'],                       key_columns: ['EmployeeKey','EmployeeID','FullName','Role','EmploymentType','AwardClassification','Region','ScreeningStatus','ScreeningExpiryDate','IsActive'] },
    { name: 'Dim_Location',        type: 'Standard', hierarchies: ['State → Region → Suburb → Location'],                     key_columns: ['LocationKey','LocationName','LocationType','Suburb','State','Postcode','Region','SILCapacity'] },
    { name: 'Dim_Date',            type: 'Standard', hierarchies: ['FiscalYear → FiscalQuarter → FiscalMonth → Week → Day'], key_columns: ['DateKey','Date','Day','Week','Month','MonthName','Quarter','CalendarYear','FiscalYear','FiscalQuarter','FiscalMonth','IsWeekend','IsPublicHoliday','PublicHolidayName'] },
  ],
  relationships: [
    { from: 'Fact_ServiceDelivery[DateKey]',            to: 'Dim_Date[DateKey]',              cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Shift date — active' },
    { from: 'Fact_ServiceDelivery[ParticipantKey]',     to: 'Dim_Participant[ParticipantKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ServiceDelivery[EmployeeKey]',        to: 'Dim_Employee[EmployeeKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ServiceDelivery[SupportItemKey]',     to: 'Dim_SupportItem[SupportItemKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ServiceDelivery[LocationKey]',        to: 'Dim_Location[LocationKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Claims[DateKey]',                     to: 'Dim_Date[DateKey]',               cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Submission date — active' },
    { from: 'Fact_Claims[ServiceDateKey]',              to: 'Dim_Date[DateKey]',               cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Service date — USERELATIONSHIP()' },
    { from: 'Fact_Claims[ParticipantKey]',              to: 'Dim_Participant[ParticipantKey]',  cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_PlanUtilisation[ParticipantKey]',     to: 'Dim_Participant[ParticipantKey]',  cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_PlanUtilisation[DateKey]',            to: 'Dim_Date[DateKey]',               cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Snapshot date' },
    { from: 'Fact_PlanUtilisation[SupportCategoryKey]', to: 'Dim_SupportCategory[SupportCategoryKey]', cardinality: 'Many:One', direction: 'Single', active: true, notes: '' },
    { from: 'Fact_Roster[EmployeeKey]',                 to: 'Dim_Employee[EmployeeKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Roster[DateKey]',                     to: 'Dim_Date[DateKey]',               cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Roster[ParticipantKey]',              to: 'Dim_Participant[ParticipantKey]',  cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Incidents[ParticipantKey]',           to: 'Dim_Participant[ParticipantKey]',  cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Incidents[DateKey]',                  to: 'Dim_Date[DateKey]',               cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Incidents[EmployeeKey]',              to: 'Dim_Employee[EmployeeKey]',        cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
  ],
  measures: [
    { name: 'Revenue',                 folder: 'Revenue / Base',              format: '$#,##0',  dax: `Revenue =\nSUMX(Fact_ServiceDelivery, Fact_ServiceDelivery[BillableHours] * Fact_ServiceDelivery[NDISUnitRate])`, desc: 'Billable revenue at NDIS PAPL rates' },
    { name: 'Delivered Hours',         folder: 'Utilisation / Base',          format: '#,##0.0', dax: `Delivered Hours = SUM(Fact_ServiceDelivery[DeliveredHours])`,                                                     desc: 'Total confirmed delivered support hours' },
    { name: 'Billable Hours',          folder: 'Utilisation / Base',          format: '#,##0.0', dax: `Billable Hours = SUM(Fact_ServiceDelivery[BillableHours])`,                                                       desc: 'Hours eligible for NDIS claim' },
    { name: 'Unbillable Hours',        folder: 'Utilisation / Base',          format: '#,##0.0', dax: `Unbillable Hours = [Delivered Hours] - [Billable Hours]`,                                                         desc: 'Delivered hours not claimable' },
    { name: 'Billable Utilisation %',  folder: 'Utilisation / Ratios',        format: '0.0%',    dax: `Billable Utilisation % = DIVIDE([Billable Hours], [Delivered Hours], 0)`,                                         desc: 'Billable hours as % of delivered hours' },
    { name: 'Staff Utilisation %',     folder: 'Utilisation / Ratios',        format: '0.0%',    dax: `Staff Utilisation % = DIVIDE([Delivered Hours], SUM(Fact_Roster[RosteredHours]), 0)`,                             desc: 'Delivered vs rostered hours' },
    { name: 'Claim Approval Rate',     folder: 'Claims / Ratios',             format: '0.0%',    dax: `Claim Approval Rate =\nDIVIDE(\n    CALCULATE(SUM(Fact_Claims[ClaimAmount]), Fact_Claims[ClaimStatus] = "Approved"),\n    SUM(Fact_Claims[ClaimAmount]), 0\n)`, desc: 'Approved claim value as % submitted' },
    { name: 'Claim Rejection Rate',    folder: 'Claims / Ratios',             format: '0.0%',    dax: `Claim Rejection Rate =\nDIVIDE(\n    CALCULATE(SUM(Fact_Claims[RejectedAmount]), Fact_Claims[ClaimStatus] = "Rejected"),\n    SUM(Fact_Claims[ClaimAmount]), 0\n)`, desc: 'Rejected value as % of submitted' },
    { name: 'Plan Utilisation %',      folder: 'Participants / Budget',       format: '0.0%',    dax: `Plan Utilisation % = DIVIDE(SUM(Fact_PlanUtilisation[AmountUtilised]), SUM(Fact_PlanUtilisation[PlanBudget]), 0)`, desc: 'Cumulative plan spend as % of budget' },
    { name: 'Avg Plan Utilisation %',  folder: 'Participants / Budget',       format: '0.0%',    dax: `Avg Plan Utilisation % =\nAVERAGEX(VALUES(Dim_Participant[ParticipantKey]), [Plan Utilisation %])`,               desc: 'Average plan utilisation across participants' },
    { name: 'Active Participants',     folder: 'Participants / Core',         format: '#,##0',   dax: `Active Participants =\nCALCULATE(\n    DISTINCTCOUNT(Fact_ServiceDelivery[ParticipantKey]),\n    Fact_ServiceDelivery[DeliveredHours] > 0\n)`, desc: 'Participants with at least one delivered hour' },
    { name: 'Revenue per Participant', folder: 'Revenue / Ratios',            format: '$#,##0',  dax: `Revenue per Participant = DIVIDE([Revenue], [Active Participants], 0)`,                                            desc: 'Average revenue per active participant' },
    { name: 'SIL Occupancy %',         folder: 'Utilisation / SIL',           format: '0.0%',    dax: `SIL Occupancy % =\nDIVIDE(\n    CALCULATE(DISTINCTCOUNT(Fact_ServiceDelivery[ParticipantKey]), Dim_Location[LocationType] = "SIL House"),\n    CALCULATE(SUM(Dim_Location[SILCapacity]), Dim_Location[LocationType] = "SIL House"),\n    0\n)`, desc: 'SIL participants vs licensed capacity' },
    { name: 'Plans Expiring 30 Days',  folder: 'Participants / Risk',         format: '#,##0',   dax: `Plans Expiring 30 Days =\nCALCULATE(\n    DISTINCTCOUNT(Dim_Participant[ParticipantKey]),\n    Dim_Participant[IsActive] = TRUE(),\n    Dim_Participant[PlanEndDate] >= TODAY(),\n    Dim_Participant[PlanEndDate] <= TODAY() + 30\n)`, desc: 'Plans expiring within 30 days' },
    { name: 'Incident Rate',           folder: 'Compliance / Safety',         format: '#,##0.0', dax: `Incident Rate = DIVIDE(COUNTROWS(Fact_Incidents), DIVIDE([Delivered Hours], 1000), 0)`,                            desc: 'Incidents per 1,000 delivered hours' },
    { name: 'Revenue YTD',             folder: 'Revenue / Time Intelligence', format: '$#,##0',  dax: `Revenue YTD = TOTALYTD([Revenue], Dim_Date[Date], "30/06")`,                                                       desc: 'Cumulative revenue from 1 July' },
    { name: 'Revenue PY',              folder: 'Revenue / Time Intelligence', format: '$#,##0',  dax: `Revenue PY = CALCULATE([Revenue], SAMEPERIODLASTYEAR(Dim_Date[Date]))`,                                            desc: 'Revenue same period prior year' },
    { name: 'Revenue Growth %',        folder: 'Revenue / Variance',          format: '0.0%',    dax: `Revenue Growth % = DIVIDE([Revenue] - [Revenue PY], [Revenue PY], 0)`,                                            desc: 'Year-on-year revenue growth' },
  ],
  kpis: [
    { name: 'Billable Utilisation',  measure: 'Billable Utilisation %',    target: '> 80%',           good: '> 80%',   warn: '70–80%',      critical: '< 70%',          owner: 'Operations Manager',   cadence: 'Weekly'  },
    { name: 'Plan Utilisation',      measure: 'Avg Plan Utilisation %',    target: '85–95%',           good: '85–95%',  warn: '70–85%',      critical: '< 70% or > 95%', owner: 'Support Coordinators', cadence: 'Monthly' },
    { name: 'Claim Approval Rate',   measure: 'Claim Approval Rate',       target: '> 98%',            good: '> 98%',   warn: '95–98%',      critical: '< 95%',          owner: 'Finance Manager',      cadence: 'Weekly'  },
    { name: 'Active Participants',   measure: 'Active Participants',       target: 'Growth MoM',       good: 'Growing', warn: 'Flat',        critical: 'Declining',      owner: 'CEO',                  cadence: 'Monthly' },
    { name: 'SIL Occupancy',         measure: 'SIL Occupancy %',           target: '> 95%',            good: '> 95%',   warn: '85–95%',      critical: '< 85%',          owner: 'SIL Manager',          cadence: 'Daily'   },
    { name: 'Staff Utilisation',     measure: 'Staff Utilisation %',       target: '75–90%',           good: '75–90%',  warn: '65–75%',      critical: '< 65%',          owner: 'Operations Manager',   cadence: 'Weekly'  },
    { name: 'Revenue Growth',        measure: 'Revenue Growth %',          target: '> 10% YoY',        good: '> 10%',   warn: '0–10%',       critical: '< 0%',           owner: 'CFO',                  cadence: 'Monthly' },
    { name: 'Incident Rate',         measure: 'Incident Rate',             target: '< 2 per 1000 hrs', good: '< 2',     warn: '2–5',         critical: '> 5',            owner: 'Quality & Safety',     cadence: 'Monthly' },
  ],
  pages: [
    { name: 'Executive Summary',      layout: 'Executive',   audience: 'CEO, CFO, Board',                       purpose: 'Top-line revenue, participants, utilisation, claims health',           slicers: ['Fiscal Year','Month','Region','Support Category'],   visuals: [{ type:'Card', title:'Revenue MTD' },{ type:'Card', title:'Active Participants' },{ type:'Card', title:'Billable Utilisation %' },{ type:'Card', title:'Claim Approval Rate' },{ type:'Line', title:'Monthly Revenue vs Prior Year' },{ type:'Bar', title:'Revenue by Support Category' },{ type:'Gauge', title:'Avg Plan Utilisation %' },{ type:'Card', title:'Plans Expiring 30 Days' }] },
    { name: 'Participant Dashboard',  layout: 'Analytical',  audience: 'Service Managers, Support Coordinators', purpose: 'Plan health, utilisation, and delivery status per participant',       slicers: ['Support Category','Funding Type','Region','SC Name'], visuals: [{ type:'Matrix', title:'Participant × Category — Budget / Utilised / Remaining' },{ type:'Bar', title:'Plan Utilisation % by Participant' },{ type:'Card', title:'Participants at Risk' },{ type:'Table', title:'Plans Expiring 30/60/90 Days' }] },
    { name: 'Workforce & Rostering',  layout: 'Operational', audience: 'Operations Managers, Team Leaders',      purpose: 'Billable vs delivered hours, roster efficiency, staff performance',  slicers: ['Employee','Region','Team','Week'],                    visuals: [{ type:'KPI', title:'Delivered vs Rostered Hours' },{ type:'Bar', title:'Billable Utilisation % by Employee' },{ type:'Matrix', title:'Employee × Day of Week Heatmap' },{ type:'Table', title:'Workers Below Threshold' }] },
    { name: 'Claims & Revenue',       layout: 'Analytical',  audience: 'Finance Manager, Plan Managers',         purpose: 'Claim submission, approvals, rejections, and payment lag',          slicers: ['Claim Status','Support Category','Date Range'],      visuals: [{ type:'Card', title:'Claims Submitted' },{ type:'Card', title:'Approved Amount' },{ type:'Card', title:'Rejected Amount' },{ type:'Waterfall', title:'Revenue: Submitted → Paid' },{ type:'Bar', title:'Rejection Rate by Support Item' }] },
    { name: 'SIL Occupancy',          layout: 'Operational', audience: 'SIL Managers, Operations',               purpose: 'SIL house occupancy, vacancies, and revenue per house',             slicers: ['State','Region','House'],                            visuals: [{ type:'Gauge', title:'Portfolio SIL Occupancy %' },{ type:'Table', title:'Houses with Vacancies' },{ type:'Bar', title:'Revenue per SIL House' },{ type:'Line', title:'Occupancy Trend 12M' }] },
    { name: 'Incidents & Compliance', layout: 'Operational', audience: 'Quality & Safety, CEO',                  purpose: 'Incident rates, resolution times, notifiable events, worker compliance', slicers: ['Incident Type','Severity','Location','Date Range'], visuals: [{ type:'Card', title:'Total Incidents' },{ type:'Card', title:'Notifiable Incidents' },{ type:'Bar', title:'Incidents by Type' },{ type:'Line', title:'Monthly Incident Trend' },{ type:'Table', title:'Worker Compliance Matrix' }] },
  ],
  execQuestions: [
    'What is our current billable utilisation rate and how does it compare to last month?',
    'Which support categories are generating the most revenue and which are underperforming?',
    'How many participant plans expire in the next 30 days with budget remaining?',
    'What is our claim rejection rate and what are the primary rejection reasons?',
    'Which SIL houses have vacancies and what is the weekly financial impact?',
    'Which workers have billable utilisation below the 75% threshold?',
    'What percentage of plans are at risk of under-utilisation?',
    'How many notifiable incidents are unresolved beyond required timeframes?',
    'What is our revenue per participant trend vs prior year?',
    'Which regions are growing participant numbers and which are declining?',
  ],
  security: {
    rls_required: true,
    roles: [
      { role: 'Regional Manager',    table: 'Dim_Location',   dax: '[Region] = LOOKUPVALUE(UserRegions[Region], UserRegions[UPN], USERPRINCIPALNAME())' },
      { role: 'Support Coordinator', table: 'Dim_Participant', dax: '[SupportCoordinatorUPN] = USERPRINCIPALNAME()' },
      { role: 'SIL Manager',         table: 'Dim_Location',   dax: '[LocationType] = "SIL House" && [ManagerUPN] = USERPRINCIPALNAME()' },
    ],
    pii_columns: ['Dim_Participant[FirstName]','Dim_Participant[LastName]','Dim_Participant[DateOfBirth]','Dim_Participant[ParticipantID]','Dim_Employee[FirstName]','Dim_Employee[LastName]'],
    sensitivity_label: 'Highly Confidential',
    notes: [
      'NDIS participant data is sensitive personal information under the Privacy Act 1988.',
      'Apply Microsoft Purview Highly Confidential label to all datasets.',
      'Mask PII in all non-production environments.',
      'Commission audit reports require unfiltered access — restrict to Compliance Officers.',
    ],
  },
  semanticNotes: [
    'NDIS price limits change annually 1 July. Dim_SupportItem needs EffectiveFrom/EffectiveTo columns.',
    'Fact_Claims has two date roles — submission (active) and service date (inactive, USERELATIONSHIP()).',
    'Plan budget tracking uses PlanStartDate/PlanEndDate — not fiscal or calendar year.',
    'Fact_PlanUtilisation is a periodic snapshot — use LASTNONBLANK() for current budget remaining.',
    'Unbillable hours must be captured at fact grain, not derived only at measure layer.',
    'Group sessions require IsGroupSession flag and GroupParticipants count.',
    'All measures in _Measures table. Folders: Revenue / Utilisation / Participants / Claims / Compliance.',
  ],
};

const PACK_GOVERNMENT = {
  code: 'GOV', icon: '🏛️', tier: 1,
  description: 'Australian government organisations across Federal, State/Territory, and Local Government tiers. Funded via parliamentary appropriations. Performance measured against program outcomes, budget compliance, and service delivery targets under PGPA and equivalent state frameworks.',
  signals: [
    'appropriation','program outcome','grants','acquittal','fte establishment',
    'departmental','ministerial','anao','portfolio','aps','ses','local government',
    'rates and charges','budget paper','senate estimates','public service','grant round',
    'pgpa','cost centre','budget variance','kpi achievement','annual report',
    'procurement','austender','appropriation bill','corporate plan','myefo',
  ],
  capabilities: [
    'Budget and appropriation management',
    'Program performance monitoring (PBS / Corporate Plan)',
    'Grant administration and acquittals',
    'Procurement and contract management (AusTender)',
    'Workforce planning and HR analytics',
    'Policy delivery tracking',
    'Citizen and community service delivery',
    'Risk and audit management',
    'Parliamentary and ministerial reporting',
    'Asset and infrastructure management',
  ],
  processes: [
    'Budget appropriation → program allocation → expenditure monitoring → variance reporting',
    'Program design → milestone planning → delivery → outcome measurement → Annual Report',
    'Grant application → assessment → approval → disbursement → acquittal → ANAO audit',
    'Procurement planning → tendering → contract award → supplier performance → payment',
    'Workforce planning → recruitment → onboarding → performance → separation',
    'Risk identification → assessment → treatment → Audit Committee reporting',
    'Parliamentary estimates → Senate Estimates briefing → Questions on Notice response',
  ],
  factTables: [
    {
      name: 'Fact_Expenditure',
      grain: 'One row = one GL transaction per cost centre per date',
      source: 'Finance System (SAP / TechOne / Oracle)',
      columns: [
        { name: 'ExpenditureKey',      type: 'INT',     desc: 'Surrogate key' },
        { name: 'AgencyKey',           type: 'INT',     desc: 'FK → Dim_Agency' },
        { name: 'ProgramKey',          type: 'INT',     desc: 'FK → Dim_Program' },
        { name: 'BudgetLineKey',       type: 'INT',     desc: 'FK → Dim_BudgetLine' },
        { name: 'SupplierKey',         type: 'INT',     desc: 'FK → Dim_Supplier' },
        { name: 'DateKey',             type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'AppropriationAmount', type: 'DECIMAL', desc: 'Approved budget allocation' },
        { name: 'CommittedAmount',     type: 'DECIMAL', desc: 'Purchase orders raised' },
        { name: 'ActualExpenditure',   type: 'DECIMAL', desc: 'Invoices paid / accruals' },
        { name: 'ForecastExpenditure', type: 'DECIMAL', desc: 'Projected full-year spend' },
        { name: 'ExpenseType',         type: 'VARCHAR', desc: 'Operating / Capital / Transfer / Grant' },
        { name: 'FinancialYear',       type: 'VARCHAR', desc: 'e.g. 2025-26' },
      ],
    },
    {
      name: 'Fact_ProgramPerformance',
      grain: 'One row = one KPI result per program per reporting period',
      source: 'Performance Management System',
      columns: [
        { name: 'PerformanceKey',  type: 'INT',     desc: 'Surrogate key' },
        { name: 'ProgramKey',      type: 'INT',     desc: 'FK → Dim_Program' },
        { name: 'KPIKey',          type: 'INT',     desc: 'FK → Dim_KPI' },
        { name: 'DateKey',         type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'TargetValue',     type: 'DECIMAL', desc: 'KPI target for period' },
        { name: 'ActualValue',     type: 'DECIMAL', desc: 'Achieved value' },
        { name: 'VarianceValue',   type: 'DECIMAL', desc: 'Actual − Target' },
        { name: 'RAGStatus',       type: 'VARCHAR', desc: 'Red / Amber / Green' },
        { name: 'ReportingPeriod', type: 'VARCHAR', desc: 'Quarter / Month / Annual' },
        { name: 'EvidenceCount',   type: 'INT',     desc: 'Supporting evidence documents' },
      ],
    },
    {
      name: 'Fact_Grants',
      grain: 'One row = one grant payment transaction',
      source: 'Grants Management System (GrantConnect)',
      columns: [
        { name: 'GrantKey',            type: 'INT',     desc: 'Surrogate key' },
        { name: 'ProgramKey',          type: 'INT',     desc: 'FK → Dim_Program' },
        { name: 'RecipientKey',        type: 'INT',     desc: 'FK → Dim_GrantRecipient' },
        { name: 'ApprovalDateKey',     type: 'INT',     desc: 'FK → Dim_Date (approval — active)' },
        { name: 'DisbursementDateKey', type: 'INT',     desc: 'FK → Dim_Date (payment — inactive)' },
        { name: 'AcquittalDateKey',    type: 'INT',     desc: 'FK → Dim_Date (acquittal — inactive)' },
        { name: 'ApprovedAmount',      type: 'DECIMAL', desc: 'Approved grant value ($)' },
        { name: 'DisbursedAmount',     type: 'DECIMAL', desc: 'Amount paid to recipient' },
        { name: 'AcquittedAmount',     type: 'DECIMAL', desc: 'Amount formally acquitted' },
        { name: 'UnacquittedAmount',   type: 'DECIMAL', desc: 'Disbursed − Acquitted' },
        { name: 'GrantStatus',         type: 'VARCHAR', desc: 'Active / Acquitted / Overdue / Closed' },
      ],
    },
    {
      name: 'Fact_Contracts',
      grain: 'One row = one contract record',
      source: 'Procurement System / AusTender',
      columns: [
        { name: 'ContractKey',       type: 'INT',     desc: 'Surrogate key' },
        { name: 'SupplierKey',       type: 'INT',     desc: 'FK → Dim_Supplier' },
        { name: 'ProgramKey',        type: 'INT',     desc: 'FK → Dim_Program' },
        { name: 'StartDateKey',      type: 'INT',     desc: 'FK → Dim_Date (start — active)' },
        { name: 'EndDateKey',        type: 'INT',     desc: 'FK → Dim_Date (end — inactive)' },
        { name: 'ContractValue',     type: 'DECIMAL', desc: 'Total contract value ($)' },
        { name: 'AmountPaid',        type: 'DECIMAL', desc: 'Cumulative payments made' },
        { name: 'AmountRemaining',   type: 'DECIMAL', desc: 'ContractValue − AmountPaid' },
        { name: 'ProcurementMethod', type: 'VARCHAR', desc: 'Open Tender / RFQ / Panel / Direct Source' },
        { name: 'IsSME',             type: 'BIT',     desc: 'SME supplier flag' },
        { name: 'IsIndigenous',      type: 'BIT',     desc: 'Indigenous supplier flag' },
        { name: 'IsActive',          type: 'BIT',     desc: 'Active contract flag' },
      ],
    },
    {
      name: 'Fact_Workforce',
      grain: 'One row = one employee × one month-end snapshot',
      source: 'HR / Payroll System',
      columns: [
        { name: 'WorkforceKey', type: 'INT',     desc: 'Surrogate key' },
        { name: 'EmployeeKey',  type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'AgencyKey',    type: 'INT',     desc: 'FK → Dim_Agency' },
        { name: 'DateKey',      type: 'INT',     desc: 'FK → Dim_Date (month-end snapshot)' },
        { name: 'FTE',          type: 'DECIMAL', desc: 'Full-time equivalent' },
        { name: 'HeadCount',    type: 'INT',     desc: 'Headcount (persons)' },
        { name: 'SalaryBand',   type: 'VARCHAR', desc: 'APS1–6 / EL1–2 / SES1–3' },
        { name: 'IsOngoing',    type: 'BIT',     desc: 'Ongoing vs non-ongoing / labour hire' },
        { name: 'AbsenceDays',  type: 'DECIMAL', desc: 'Leave days in period' },
        { name: 'TurnoverFlag', type: 'BIT',     desc: 'Separated in period' },
      ],
    },
  ],
  dimensions: [
    { name: 'Dim_Agency',         type: 'Standard', hierarchies: ['Portfolio → Agency → Division → Branch'],      key_columns: ['AgencyCode','AgencyName','Tier','Portfolio','Minister','Secretary'] },
    { name: 'Dim_Program',        type: 'Standard', hierarchies: ['Outcome → Output → Program → Activity'],       key_columns: ['ProgramCode','ProgramName','OutcomeStatement','PolicyArea','ProgramManager','StartDate','EndDate'] },
    { name: 'Dim_BudgetLine',     type: 'Standard', hierarchies: ['ExpenseCategory → GLAccount'],                 key_columns: ['BudgetCode','BudgetDescription','ExpenseCategory','CapitalOrRecurrent','GLAccountCode'] },
    { name: 'Dim_GrantRecipient', type: 'Standard', hierarchies: ['State → LGA → Recipient'],                     key_columns: ['RecipientName','ABN','RecipientType','State','Electorate'] },
    { name: 'Dim_Supplier',       type: 'SCD2',     hierarchies: ['PanelCategory → Supplier'],                    key_columns: ['SupplierName','ABN','PanelCategory','SMEFlag','IndigenousSupplierFlag','State'] },
    { name: 'Dim_Employee',       type: 'SCD2',     hierarchies: ['Agency → Division → Branch → Employee'],       key_columns: ['Classification','EmploymentType','GenderIdentity','AboriginalTorresStraitIslanderFlag'] },
    { name: 'Dim_KPI',            type: 'Standard', hierarchies: ['Program → KPI'],                               key_columns: ['KPIName','KPIType','Unit','ReportingFrequency','PBSRef','IsQuantitative'] },
    { name: 'Dim_Date',           type: 'Standard', hierarchies: ['FiscalYear → FiscalQuarter → Month → Day'],   key_columns: ['DateKey','Date','FiscalYear','FinancialYear','Quarter','Month','BudgetPeriod','IsPublicHoliday'] },
  ],
  relationships: [
    { from: 'Fact_Expenditure[DateKey]',           to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Expenditure[ProgramKey]',        to: 'Dim_Program[ProgramKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Expenditure[BudgetLineKey]',     to: 'Dim_BudgetLine[BudgetLineKey]',     cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Expenditure[AgencyKey]',         to: 'Dim_Agency[AgencyKey]',             cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ProgramPerformance[ProgramKey]', to: 'Dim_Program[ProgramKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ProgramPerformance[DateKey]',    to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ProgramPerformance[KPIKey]',     to: 'Dim_KPI[KPIKey]',                   cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Grants[ApprovalDateKey]',        to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Approval date — active' },
    { from: 'Fact_Grants[DisbursementDateKey]',    to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Disbursement — USERELATIONSHIP()' },
    { from: 'Fact_Grants[AcquittalDateKey]',       to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Acquittal — USERELATIONSHIP()' },
    { from: 'Fact_Grants[RecipientKey]',           to: 'Dim_GrantRecipient[RecipientKey]',  cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Grants[ProgramKey]',             to: 'Dim_Program[ProgramKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Contracts[StartDateKey]',        to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Start date — active' },
    { from: 'Fact_Contracts[EndDateKey]',          to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: false, notes: 'End date — USERELATIONSHIP()' },
    { from: 'Fact_Contracts[SupplierKey]',         to: 'Dim_Supplier[SupplierKey]',         cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Workforce[EmployeeKey]',         to: 'Dim_Employee[EmployeeKey]',         cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Workforce[DateKey]',             to: 'Dim_Date[DateKey]',                 cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Month-end snapshot' },
    { from: 'Fact_Workforce[AgencyKey]',           to: 'Dim_Agency[AgencyKey]',             cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
  ],
  measures: [
    { name: 'Total Expenditure',    folder: 'Budget / Core',              format: '$#,##0',  dax: `Total Expenditure = SUM(Fact_Expenditure[ActualExpenditure])`,                                                                                                               desc: 'Total actual expenditure' },
    { name: 'Total Appropriation',  folder: 'Budget / Core',              format: '$#,##0',  dax: `Total Appropriation = SUM(Fact_Expenditure[AppropriationAmount])`,                                                                                                           desc: 'Total approved appropriation' },
    { name: 'Budget Variance',      folder: 'Budget / Core',              format: '$#,##0',  dax: `Budget Variance = [Total Appropriation] - [Total Expenditure]`,                                                                                                              desc: 'Remaining unspent appropriation' },
    { name: 'Budget Utilisation %', folder: 'Budget / Core',              format: '0.0%',    dax: `Budget Utilisation % = DIVIDE([Total Expenditure], [Total Appropriation], 0)`,                                                                                               desc: 'Actual spend as % of appropriation' },
    { name: 'Commitment Rate %',    folder: 'Budget / Core',              format: '0.0%',    dax: `Commitment Rate % = DIVIDE(SUM(Fact_Expenditure[CommittedAmount]), [Total Appropriation], 0)`,                                                                                desc: 'Purchase orders as % of appropriation' },
    { name: 'KPI Achievement Rate', folder: 'Program / Performance',      format: '0.0%',    dax: `KPI Achievement Rate =\nDIVIDE(\n    CALCULATE(COUNTROWS(Fact_ProgramPerformance), Fact_ProgramPerformance[RAGStatus] = "Green"),\n    COUNTROWS(Fact_ProgramPerformance), 0\n)`, desc: '% of KPIs rated Green' },
    { name: 'Programs at Risk',     folder: 'Program / Performance',      format: '#,##0',   dax: `Programs at Risk =\nCALCULATE(\n    DISTINCTCOUNT(Fact_ProgramPerformance[ProgramKey]),\n    Fact_ProgramPerformance[RAGStatus] IN {"Red","Amber"}\n)`,                        desc: 'Programs rated Red or Amber' },
    { name: 'Grants Disbursed',     folder: 'Grants / Core',              format: '$#,##0',  dax: `Grants Disbursed = SUM(Fact_Grants[DisbursedAmount])`,                                                                                                                       desc: 'Total grants disbursed' },
    { name: 'Grants Unacquitted',   folder: 'Grants / Core',              format: '$#,##0',  dax: `Grants Unacquitted = SUM(Fact_Grants[UnacquittedAmount])`,                                                                                                                   desc: 'Disbursed grants not yet acquitted' },
    { name: 'Grant Acquittal Rate', folder: 'Grants / Ratios',            format: '0.0%',    dax: `Grant Acquittal Rate = DIVIDE(SUM(Fact_Grants[AcquittedAmount]), SUM(Fact_Grants[DisbursedAmount]), 0)`,                                                                     desc: 'Acquitted as % of total disbursed' },
    { name: 'Total FTE',            folder: 'Workforce / Core',           format: '#,##0.0', dax: `Total FTE = SUM(Fact_Workforce[FTE])`,                                                                                                                                       desc: 'FTE at snapshot date' },
    { name: 'Non-Ongoing FTE %',    folder: 'Workforce / Ratios',         format: '0.0%',    dax: `Non-Ongoing FTE % =\nDIVIDE(\n    CALCULATE(SUM(Fact_Workforce[FTE]), Fact_Workforce[IsOngoing] = FALSE()),\n    SUM(Fact_Workforce[FTE]), 0\n)`,                             desc: 'Non-ongoing / labour hire FTE as % of total' },
    { name: 'Turnover Rate %',      folder: 'Workforce / Ratios',         format: '0.0%',    dax: `Turnover Rate % = DIVIDE(CALCULATE(COUNTROWS(Fact_Workforce), Fact_Workforce[TurnoverFlag] = 1), AVERAGE(Fact_Workforce[HeadCount]), 0)`,                                    desc: 'Separations as % of average headcount' },
    { name: 'Expenditure YTD',      folder: 'Budget / Time Intelligence', format: '$#,##0',  dax: `Expenditure YTD = TOTALYTD(SUM(Fact_Expenditure[ActualExpenditure]), Dim_Date[Date], "30/06")`,                                                                              desc: 'Cumulative expenditure from 1 July' },
    { name: 'Expenditure PY',       folder: 'Budget / Time Intelligence', format: '$#,##0',  dax: `Expenditure PY = CALCULATE([Total Expenditure], SAMEPERIODLASTYEAR(Dim_Date[Date]))`,                                                                                        desc: 'Expenditure same period prior year' },
    { name: 'SME Spend %',          folder: 'Contracts / Diversity',      format: '0.0%',    dax: `SME Spend % = DIVIDE(CALCULATE(SUM(Fact_Contracts[AmountPaid]), Fact_Contracts[IsSME] = 1), SUM(Fact_Contracts[AmountPaid]), 0)`,                                            desc: 'SME spend as % of total contracts' },
  ],
  kpis: [
    { name: 'Budget Utilisation',     measure: 'Budget Utilisation %',  target: '95–100% by 30 Jun', good: '95–100%', warn: '85–95%', critical: '< 85% or > 100%', owner: 'CFO',              cadence: 'Monthly'   },
    { name: 'Program KPI Green Rate', measure: 'KPI Achievement Rate',  target: '> 80% Green',       good: '> 80%',   warn: '60–80%',critical: '< 60%',           owner: 'Deputy Secretary', cadence: 'Quarterly' },
    { name: 'Grant Acquittal Rate',   measure: 'Grant Acquittal Rate',  target: '> 95%',             good: '> 95%',   warn: '85–95%',critical: '< 85%',           owner: 'Program Managers', cadence: 'Quarterly' },
    { name: 'FTE vs Approved',        measure: 'Total FTE',             target: '≤ approved FTE',    good: '95–100%', warn: '90–95%',critical: '< 90%',           owner: 'CHRO',             cadence: 'Monthly'   },
    { name: 'Budget Variance',        measure: 'Budget Variance',       target: '< 2% underspend',   good: '< 2%',    warn: '2–5%',  critical: '> 5%',            owner: 'CFO',              cadence: 'Monthly'   },
    { name: 'Non-Ongoing FTE',        measure: 'Non-Ongoing FTE %',     target: '< 15%',             good: '< 15%',   warn: '15–20%',critical: '> 20%',           owner: 'CHRO',             cadence: 'Monthly'   },
    { name: 'Programs at Risk',       measure: 'Programs at Risk',      target: '0 Red programs',    good: '0',       warn: '1–3',   critical: '> 3',             owner: 'Deputy Secretary', cadence: 'Quarterly' },
  ],
  pages: [
    { name: 'Minister / Secretary Dashboard', layout: 'Executive',   audience: 'Secretary, Minister',   purpose: 'Top-level performance for executive briefings',                     slicers: ['Portfolio','Program','Financial Year'],      visuals: [{ type:'KPI', title:'Programs On-Track %' },{ type:'Card', title:'Expenditure vs Appropriation' },{ type:'Card', title:'FTE vs Approved' },{ type:'Matrix', title:'Program RAG Status' }] },
    { name: 'Budget & Expenditure',           layout: 'Analytical',  audience: 'CFO, Finance Branch',   purpose: 'Expenditure vs appropriation by program, division, expense type',  slicers: ['Program','Division','Expense Type','Month'], visuals: [{ type:'Waterfall', title:'Appropriation → Committed → Actual → Remaining' },{ type:'Bar', title:'Expenditure by Division' },{ type:'Line', title:'YTD Trend' },{ type:'Matrix', title:'Cost Centre Detail' }] },
    { name: 'Program Performance',            layout: 'Analytical',  audience: 'SES, Program Managers', purpose: 'PBS KPIs — RAG status, target vs actual, trend',                  slicers: ['Outcome','Program','Quarter'],               visuals: [{ type:'Table', title:'KPI RAG Status Matrix' },{ type:'Bar', title:'Programs Rated Red/Amber' },{ type:'Line', title:'Achievement Trend' }] },
    { name: 'Grants Management',              layout: 'Operational', audience: 'Grants Team, Audit',    purpose: 'Pipeline, disbursements, and acquittal compliance',               slicers: ['Program','State','Grant Status'],            visuals: [{ type:'Funnel', title:'Grant Lifecycle Pipeline' },{ type:'Map', title:'Grants by State / Electorate' },{ type:'Table', title:'Overdue Acquittals' }] },
    { name: 'Procurement & Contracts',        layout: 'Analytical',  audience: 'Procurement, Finance',  purpose: 'Contract portfolio, expiry risk, supplier diversity',             slicers: ['Agency','Procurement Method'],               visuals: [{ type:'Bar', title:'Contract Value by Method' },{ type:'Table', title:'Contracts Expiring 30/60/90 Days' },{ type:'Card', title:'SME Spend %' }] },
    { name: 'Workforce Analytics',            layout: 'Analytical',  audience: 'CHRO, Division Heads',  purpose: 'FTE, classification, non-ongoing ratio, diversity',              slicers: ['Agency','Division','Classification','Month'],visuals: [{ type:'Bar', title:'FTE by APS Classification' },{ type:'Card', title:'Vacancy Rate %' },{ type:'Line', title:'Turnover Trend' }] },
  ],
  execQuestions: [
    'Are we on track to fully utilise our appropriation by 30 June?',
    'Which programs are rated Red or Amber against PBS KPIs this quarter?',
    'How many grants remain unacquitted beyond their due date?',
    'What is our FTE vs approved establishment?',
    'Which contracts expire in 90 days without a renewal in progress?',
    'What is our year-to-date budget variance by portfolio?',
    'How is our non-ongoing FTE ratio tracking against APS policy limits?',
    'What percentage of contract spend goes to SME and Indigenous suppliers?',
  ],
  security: {
    rls_required: true,
    roles: [
      { role: 'Agency User',      table: 'Dim_Agency', dax: '[AgencyCode] = LOOKUPVALUE(UserAgency[AgencyCode], UserAgency[UPN], USERPRINCIPALNAME())' },
      { role: 'Division Manager', table: 'Dim_Agency', dax: '[Division] = LOOKUPVALUE(UserDivision[Division], UserDivision[UPN], USERPRINCIPALNAME())' },
    ],
    pii_columns: ['Dim_Employee[FullName]','Dim_Employee[Salary]','Dim_Employee[GenderIdentity]','Dim_Employee[AboriginalTorresStraitIslanderFlag]'],
    sensitivity_label: 'Official Sensitive',
    notes: [
      'Apply ISM labels: Official / Official Sensitive / Protected as appropriate.',
      'Individual salary data restricted to HR and Finance only.',
      'Diversity data anonymised below n < 5 threshold.',
    ],
  },
  semanticNotes: [
    'Financial year is 1 July – 30 June. All TOTALYTD must use "30/06".',
    'AppropriationAmount and ActualExpenditure must be separate fact columns.',
    'Program hierarchy is ragged — use parent-child or flattened bridge table.',
    'Fact_Workforce is a monthly snapshot — use LASTNONBLANK() to avoid double-counting.',
    'Fact_Grants needs three date roles: approval (active), disbursement, acquittal (both inactive).',
    'Fact_Contracts needs two date roles: start (active), end (inactive, USERELATIONSHIP()).',
  ],
};
