/* =============================================================
   knowledgepacks-2.js  —  Professional Services · Property Management
============================================================= */
'use strict';

const PACK_PROFESSIONAL_SERVICES = {
  code: 'PROSERV', icon: '💼', tier: 1,
  description: 'Consulting, advisory, accounting, engineering, legal, and specialist service firms generating revenue through billable engagements. Revenue is time-based — billable hours captured on timesheets converted to invoices. Profitability driven by utilisation, realisation rates, average bill rates, and WIP recovery. Spans Big 4 through to boutique practices.',
  signals: [
    'billable hours','utilisation','timesheets','engagements','wip','realisation',
    'recovery rate','charge-out rate','bill rate','write-off','write-on',
    'clients','consultants','practice area','service line','retainer',
    'professional services','advisory','consulting','partners','managers',
    'revenue per consultant','debtors','work in progress','fee earner',
    'proposal','pipeline','engagement letter','scope creep',
  ],
  capabilities: [
    'Client management and relationship tracking',
    'Engagement delivery and project management',
    'Resource management and capacity planning',
    'Workforce utilisation tracking',
    'Timesheet capture and approval',
    'WIP management and billing',
    'Invoice generation and collections',
    'Profitability analysis by client, engagement, and service line',
    'Revenue forecasting and pipeline management',
    'Partner and consultant performance reporting',
  ],
  processes: [
    'Business development → proposal → engagement letter → project setup',
    'Resource planning → staff assignment → timesheet submission → approval',
    'Approved timesheets → WIP accumulation → billing review → invoice generation',
    'Invoice issued → debtor management → payment receipt → aged debtors review',
    'Engagement delivery → milestone tracking → budget vs actual → write-off / write-on',
    'Monthly billing run → WIP reconciliation → revenue recognition → P&L reporting',
    'Partner performance review → utilisation analysis → capacity planning',
  ],
  factTables: [
    {
      name: 'Fact_Timesheets',
      grain: 'One row = one timesheet line per employee per engagement per day',
      source: 'Practice Management System (MYOB AE, Xero Practice, Karbon, GreatSoft)',
      columns: [
        { name: 'TimesheetKey',     type: 'INT',     desc: 'Surrogate key' },
        { name: 'EmployeeKey',      type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'EngagementKey',    type: 'INT',     desc: 'FK → Dim_Engagement' },
        { name: 'ClientKey',        type: 'INT',     desc: 'FK → Dim_Client' },
        { name: 'ServiceLineKey',   type: 'INT',     desc: 'FK → Dim_ServiceLine' },
        { name: 'DateKey',          type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'HoursWorked',      type: 'DECIMAL', desc: 'Total hours worked' },
        { name: 'BillableHours',    type: 'DECIMAL', desc: 'Hours billable to client' },
        { name: 'NonBillableHours', type: 'DECIMAL', desc: 'Internal / non-chargeable hours' },
        { name: 'StandardRate',     type: 'DECIMAL', desc: 'Standard charge-out rate ($/hr)' },
        { name: 'WIPValue',         type: 'DECIMAL', desc: 'BillableHours × StandardRate' },
        { name: 'IsApproved',       type: 'BIT',     desc: 'Timesheet approved by manager' },
      ],
    },
    {
      name: 'Fact_Engagements',
      grain: 'One row = one engagement snapshot per reporting period',
      source: 'Practice Management System',
      columns: [
        { name: 'EngagementKey',    type: 'INT',     desc: 'Surrogate key' },
        { name: 'ClientKey',        type: 'INT',     desc: 'FK → Dim_Client' },
        { name: 'EngagementMgrKey', type: 'INT',     desc: 'FK → Dim_Employee (engagement manager)' },
        { name: 'ServiceLineKey',   type: 'INT',     desc: 'FK → Dim_ServiceLine' },
        { name: 'DateKey',          type: 'INT',     desc: 'FK → Dim_Date (snapshot — active)' },
        { name: 'StartDateKey',     type: 'INT',     desc: 'FK → Dim_Date (start — inactive)' },
        { name: 'EndDateKey',       type: 'INT',     desc: 'FK → Dim_Date (end — inactive)' },
        { name: 'BudgetFees',       type: 'DECIMAL', desc: 'Budgeted fee value ($)' },
        { name: 'ActualFees',       type: 'DECIMAL', desc: 'Fees billed to date ($)' },
        { name: 'WIPBalance',       type: 'DECIMAL', desc: 'Unbilled WIP balance ($)' },
        { name: 'WriteOffAmount',   type: 'DECIMAL', desc: 'WIP written off ($)' },
        { name: 'EngagementStatus', type: 'VARCHAR', desc: 'Active / Completed / On Hold / Lost' },
        { name: 'IsFixedFee',       type: 'BIT',     desc: 'Fixed fee vs time-and-materials' },
      ],
    },
    {
      name: 'Fact_Invoices',
      grain: 'One row = one invoice line item',
      source: 'Billing / Accounting System',
      columns: [
        { name: 'InvoiceKey',        type: 'INT',     desc: 'Surrogate key' },
        { name: 'ClientKey',         type: 'INT',     desc: 'FK → Dim_Client' },
        { name: 'EngagementKey',     type: 'INT',     desc: 'FK → Dim_Engagement' },
        { name: 'InvoiceDateKey',    type: 'INT',     desc: 'FK → Dim_Date (invoice date — active)' },
        { name: 'DueDateKey',        type: 'INT',     desc: 'FK → Dim_Date (due date — inactive)' },
        { name: 'PaidDateKey',       type: 'INT',     desc: 'FK → Dim_Date (paid date — inactive)' },
        { name: 'InvoiceAmount',     type: 'DECIMAL', desc: 'Total invoice value ($)' },
        { name: 'GSTAmount',         type: 'DECIMAL', desc: 'GST component ($)' },
        { name: 'AmountPaid',        type: 'DECIMAL', desc: 'Amount received ($)' },
        { name: 'AmountOutstanding', type: 'DECIMAL', desc: 'InvoiceAmount − AmountPaid' },
        { name: 'DaysOutstanding',   type: 'INT',     desc: 'Days since invoice date' },
        { name: 'InvoiceStatus',     type: 'VARCHAR', desc: 'Draft / Issued / Paid / Overdue / Written Off' },
      ],
    },
    {
      name: 'Fact_ResourceUtilisation',
      grain: 'One row = one employee × one week',
      source: 'Practice Management / Timesheets',
      columns: [
        { name: 'UtilisationKey',   type: 'INT',     desc: 'Surrogate key' },
        { name: 'EmployeeKey',      type: 'INT',     desc: 'FK → Dim_Employee' },
        { name: 'ServiceLineKey',   type: 'INT',     desc: 'FK → Dim_ServiceLine' },
        { name: 'DateKey',          type: 'INT',     desc: 'FK → Dim_Date (week ending)' },
        { name: 'AvailableHours',   type: 'DECIMAL', desc: 'Standard available hours' },
        { name: 'BillableHours',    type: 'DECIMAL', desc: 'Hours billed to clients' },
        { name: 'NonBillableHours', type: 'DECIMAL', desc: 'Internal / BD / training hours' },
        { name: 'LeaveHours',       type: 'DECIMAL', desc: 'Approved leave hours' },
        { name: 'UtilisationRate',  type: 'DECIMAL', desc: 'BillableHours / AvailableHours' },
      ],
    },
    {
      name: 'Fact_Pipeline',
      grain: 'One row = one opportunity / proposal snapshot',
      source: 'CRM / BD Tracking System',
      columns: [
        { name: 'PipelineKey',       type: 'INT',     desc: 'Surrogate key' },
        { name: 'ClientKey',         type: 'INT',     desc: 'FK → Dim_Client' },
        { name: 'ServiceLineKey',    type: 'INT',     desc: 'FK → Dim_ServiceLine' },
        { name: 'OwnerKey',          type: 'INT',     desc: 'FK → Dim_Employee (opportunity owner)' },
        { name: 'DateKey',           type: 'INT',     desc: 'FK → Dim_Date (snapshot)' },
        { name: 'EstimatedValue',    type: 'DECIMAL', desc: 'Estimated engagement value ($)' },
        { name: 'WeightedValue',     type: 'DECIMAL', desc: 'EstimatedValue × WinProbability' },
        { name: 'WinProbability',    type: 'DECIMAL', desc: 'Win probability (0–1)' },
        { name: 'Stage',             type: 'VARCHAR', desc: 'Lead / Qualified / Proposal / Negotiation / Won / Lost' },
        { name: 'ExpectedCloseDate', type: 'DATE',    desc: 'Expected engagement start date' },
      ],
    },
  ],
  dimensions: [
    { name: 'Dim_Client',      type: 'SCD2',     hierarchies: ['Industry → Segment → Client'],                   key_columns: ['ClientKey','ClientCode','ClientName','Industry','Segment','State','ClientPartnerKey','IsActive','ClientSince'] },
    { name: 'Dim_Employee',    type: 'SCD2',     hierarchies: ['Division → Practice → ServiceLine → Grade → Employee'], key_columns: ['EmployeeKey','EmployeeID','FullName','Grade','Role','ServiceLineKey','PracticeKey','EmploymentType','ChargeOutRate','IsPartner','IsActive'] },
    { name: 'Dim_Engagement',  type: 'Standard', hierarchies: ['Client → ServiceLine → Engagement'],              key_columns: ['EngagementKey','EngagementCode','EngagementName','ClientKey','ServiceLineKey','EngagementType','StartDate','EndDate','IsActive'] },
    { name: 'Dim_ServiceLine', type: 'Standard', hierarchies: ['Division → Practice → ServiceLine'],              key_columns: ['ServiceLineKey','ServiceLineName','PracticeKey','DivisionKey'] },
    { name: 'Dim_Practice',    type: 'Standard', hierarchies: ['Division → Practice'],                            key_columns: ['PracticeKey','PracticeName','DivisionKey','PracticeLeaderKey'] },
    { name: 'Dim_Date',        type: 'Standard', hierarchies: ['FiscalYear → FiscalQuarter → Month → Week → Day'], key_columns: ['DateKey','Date','Day','Week','Month','MonthName','Quarter','CalendarYear','FiscalYear','FiscalQuarter','FiscalMonth','IsWeekend','IsPublicHoliday'] },
  ],
  relationships: [
    { from: 'Fact_Timesheets[DateKey]',              to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Timesheets[EmployeeKey]',          to: 'Dim_Employee[EmployeeKey]',   cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Timesheets[ClientKey]',            to: 'Dim_Client[ClientKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Timesheets[ServiceLineKey]',       to: 'Dim_ServiceLine[ServiceLineKey]', cardinality: 'Many:One', direction: 'Single', active: true, notes: '' },
    { from: 'Fact_Engagements[ClientKey]',           to: 'Dim_Client[ClientKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Engagements[DateKey]',             to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Snapshot — active' },
    { from: 'Fact_Engagements[StartDateKey]',        to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Start date — USERELATIONSHIP()' },
    { from: 'Fact_Engagements[EndDateKey]',          to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: false, notes: 'End date — USERELATIONSHIP()' },
    { from: 'Fact_Engagements[ServiceLineKey]',      to: 'Dim_ServiceLine[ServiceLineKey]', cardinality: 'Many:One', direction: 'Single', active: true, notes: '' },
    { from: 'Fact_Invoices[InvoiceDateKey]',         to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Invoice date — active' },
    { from: 'Fact_Invoices[DueDateKey]',             to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Due date — USERELATIONSHIP()' },
    { from: 'Fact_Invoices[PaidDateKey]',            to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Paid date — USERELATIONSHIP()' },
    { from: 'Fact_Invoices[ClientKey]',              to: 'Dim_Client[ClientKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ResourceUtilisation[EmployeeKey]', to: 'Dim_Employee[EmployeeKey]',   cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ResourceUtilisation[DateKey]',     to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Pipeline[ClientKey]',              to: 'Dim_Client[ClientKey]',       cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Pipeline[DateKey]',                to: 'Dim_Date[DateKey]',           cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Pipeline[OwnerKey]',               to: 'Dim_Employee[EmployeeKey]',   cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
  ],
  measures: [
    { name: 'Revenue',                folder: 'Revenue / Base',              format: '$#,##0',  dax: `Revenue = SUM(Fact_Invoices[InvoiceAmount])`,                                                                                                                                                     desc: 'Total invoiced revenue (ex GST)' },
    { name: 'WIP Value',              folder: 'WIP / Base',                  format: '$#,##0',  dax: `WIP Value = SUM(Fact_Timesheets[WIPValue])`,                                                                                                                                                      desc: 'Total unbilled WIP at standard rates' },
    { name: 'Write-Off Amount',       folder: 'WIP / Base',                  format: '$#,##0',  dax: `Write-Off Amount = SUM(Fact_Engagements[WriteOffAmount])`,                                                                                                                                        desc: 'Total WIP written off' },
    { name: 'Billable Hours',         folder: 'Utilisation / Base',          format: '#,##0.0', dax: `Billable Hours = SUM(Fact_Timesheets[BillableHours])`,                                                                                                                                            desc: 'Billable hours on timesheets' },
    { name: 'Available Hours',        folder: 'Utilisation / Base',          format: '#,##0.0', dax: `Available Hours = SUM(Fact_ResourceUtilisation[AvailableHours])`,                                                                                                                                 desc: 'Standard available work hours' },
    { name: 'Billable Utilisation %', folder: 'Utilisation / Ratios',        format: '0.0%',    dax: `Billable Utilisation % = DIVIDE([Billable Hours], [Available Hours], 0)`,                                                                                                                         desc: 'Billable hours as % of available — primary efficiency KPI' },
    { name: 'Realisation %',          folder: 'Revenue / Ratios',            format: '0.0%',    dax: `Realisation % = DIVIDE([Revenue], [WIP Value], 0)`,                                                                                                                                               desc: 'Invoiced revenue as % of WIP at standard rates' },
    { name: 'Recovery Rate %',        folder: 'Revenue / Ratios',            format: '0.0%',    dax: `Recovery Rate % = DIVIDE([Revenue], CALCULATE([WIP Value], ALL(Dim_Date)), 0)`,                                                                                                                   desc: 'Revenue recovered as % of total WIP generated' },
    { name: 'Avg Bill Rate',          folder: 'Revenue / Ratios',            format: '$#,##0',  dax: `Avg Bill Rate = DIVIDE([Revenue], [Billable Hours], 0)`,                                                                                                                                          desc: 'Effective hourly rate achieved' },
    { name: 'Revenue per Consultant', folder: 'Revenue / Ratios',            format: '$#,##0',  dax: `Revenue per Consultant = DIVIDE([Revenue], DISTINCTCOUNT(Fact_Timesheets[EmployeeKey]), 0)`,                                                                                                      desc: 'Average revenue per fee earner' },
    { name: 'Debtors Outstanding',    folder: 'Collections / Base',          format: '$#,##0',  dax: `Debtors Outstanding = SUM(Fact_Invoices[AmountOutstanding])`,                                                                                                                                    desc: 'Total unpaid invoice value' },
    { name: 'Debtor Days',            folder: 'Collections / Ratios',        format: '#,##0',   dax: `Debtor Days = DIVIDE([Debtors Outstanding], DIVIDE([Revenue], 365), 0)`,                                                                                                                          desc: 'Average days to collect (DSO)' },
   ],

  kpis: [
    { name: 'Billable Utilisation',      measure: 'Billable Utilisation %', target: '> 75%',               good: '> 75%',        warn: '65–75%',   critical: '< 65%',            owner: 'Managing Partner / Practice Head', cadence: 'Weekly'  },
    { name: 'Realisation Rate',          measure: 'Realisation %',          target: '> 85%',               good: '> 85%',        warn: '75–85%',   critical: '< 75%',            owner: 'Managing Partner / CFO',           cadence: 'Monthly' },
    { name: 'WIP Value',                 measure: 'WIP Value',              target: '< 45 days lock-up',   good: '< 45 days',    warn: '45–60 days',critical: '> 60 days',        owner: 'Finance Director / Practice Mgr',  cadence: 'Weekly'  },
    { name: 'Debtor Days (DSO)',          measure: 'Debtor Days',            target: '< 45 days',           good: '< 45 days',    warn: '45–60 days',critical: '> 60 days',        owner: 'Finance Director',                 cadence: 'Weekly'  },
    { name: 'Write-Off Rate',            measure: 'Write-Off %',            target: '< 5%',                good: '< 5%',         warn: '5–10%',    critical: '> 10%',            owner: 'Managing Partner',                 cadence: 'Monthly' },
    { name: 'Revenue per Consultant',    measure: 'Revenue per Consultant', target: '> $250K per annum',   good: '> $250K',      warn: '$200–250K', critical: '< $200K',         owner: 'Managing Partner',                 cadence: 'Monthly' },
    { name: 'Average Bill Rate',         measure: 'Avg Bill Rate',          target: '>= standard rate',    good: '>= standard',  warn: '90–99% std',critical: '< 90% standard',  owner: 'Practice Head',                    cadence: 'Monthly' },
    { name: 'Engagement Profitability',  measure: 'Engagement Margin %',    target: '> 30% margin',        good: '> 30%',        warn: '20–30%',   critical: '< 20%',            owner: 'Engagement Manager',               cadence: 'Monthly' },
  ],

  pages: [
    {
      name: 'Executive Summary', layout: 'Executive',
      audience: 'Managing Partner, Board, CFO',
      purpose: 'Top-line revenue, utilisation, WIP, realisation, and debtor position for the practice',
      slicers: ['Fiscal Year','Month','Service Line','Office'],
      visuals: [
        { type: 'Card',  title: 'Revenue MTD' },
        { type: 'Card',  title: 'Billable Utilisation %' },
        { type: 'Card',  title: 'Realisation Rate %' },
        { type: 'Card',  title: 'WIP Value' },
        { type: 'Card',  title: 'Debtor Days' },
        { type: 'Line',  title: 'Revenue vs Prior Year — Monthly Trend' },
        { type: 'Bar',   title: 'Revenue by Service Line' },
        { type: 'Bar',   title: 'Billable Utilisation % by Practice Area' },
      ],
    },
    {
      name: 'Consultant Performance', layout: 'Analytical',
      audience: 'Practice Heads, Managing Partner',
      purpose: 'Per-consultant billable hours, utilisation rate, revenue, and write-offs',
      slicers: ['Service Line','Office','Month','Consultant'],
      visuals: [
        { type: 'Matrix', title: 'Consultant × Month — Billable Hours / Utilisation %' },
        { type: 'Bar',    title: 'Billable Utilisation % by Consultant vs Target' },
        { type: 'Bar',    title: 'Revenue per Consultant' },
        { type: 'Table',  title: 'Consultants Below Utilisation Threshold' },
      ],
    },
    {
      name: 'WIP & Revenue Leakage', layout: 'Analytical',
      audience: 'Finance Director, Managing Partner, Practice Heads',
      purpose: 'WIP ageing, write-offs, realisation gaps, and lock-up risk by engagement',
      slicers: ['Service Line','Client','Engagement Manager','WIP Age Band'],
      visuals: [
        { type: 'Waterfall', title: 'Revenue Bridge: WIP → Billed → Written Off → Collected' },
        { type: 'Bar',       title: 'WIP Ageing by Service Line' },
        { type: 'Bar',       title: 'Write-Off Amount by Engagement Manager' },
        { type: 'Table',     title: 'Engagements with WIP > 60 Days' },
        { type: 'KPI',       title: 'Realisation % — Actual vs Target' },
      ],
    },
    {
      name: 'Debtor Management', layout: 'Operational',
      audience: 'Finance Director, Accounts Receivable',
      purpose: 'Outstanding invoices, debtor ageing, days outstanding, and collection risk',
      slicers: ['Client','Invoice Age Band','Office','Service Line'],
      visuals: [
        { type: 'Card',  title: 'Total Debtors Outstanding' },
        { type: 'Card',  title: 'Debtor Days (DSO)' },
        { type: 'Bar',   title: 'Debtors by Age Band (30 / 60 / 90 / 90+ days)' },
        { type: 'Table', title: 'Top 20 Overdue Invoices' },
        { type: 'Line',  title: 'DSO Trend — 12 Month' },
      ],
    },
    {
      name: 'Engagement Profitability', layout: 'Analytical',
      audience: 'Engagement Managers, Practice Heads, CFO',
      purpose: 'Margin by engagement, client, and service line — identifies revenue leakage',
      slicers: ['Service Line','Client','Engagement Manager','Engagement Status'],
      visuals: [
        { type: 'Scatter', title: 'Engagement Margin % vs Revenue — bubble by WIP' },
        { type: 'Bar',     title: 'Top 10 and Bottom 10 Engagements by Margin %' },
        { type: 'Matrix',  title: 'Client × Service Line — Revenue / Margin %' },
        { type: 'Table',   title: 'Engagements with Margin < 20%' },
      ],
    },
    {
      name: 'Business Development Pipeline', layout: 'Operational',
      audience: 'Partners, Business Development, Managing Partner',
      purpose: 'Pipeline by stage, estimated value, close probability, and owner',
      slicers: ['Service Line','Office','Pipeline Stage','Expected Close Month'],
      visuals: [
        { type: 'Funnel',  title: 'Pipeline by Stage — Estimated Value' },
        { type: 'Bar',     title: 'Pipeline Value by Partner / BD Owner' },
        { type: 'Table',   title: 'Active Opportunities — Expected Close < 90 Days' },
        { type: 'Card',    title: 'Weighted Pipeline Value' },
      ],
    },
    {
      name: 'Engagement Detail', layout: 'Detail',
      audience: 'Engagement Managers',
      purpose: 'Drill-through from summary to full engagement-level timesheet and invoice detail',
      slicers: ['Engagement','Employee','Date Range'],
      visuals: [
        { type: 'Table', title: 'Timesheet Lines — Hours / WIP / Billed' },
        { type: 'Table', title: 'Invoice Register — Invoice / Due / Paid / Outstanding' },
        { type: 'Card',  title: 'Total Hours | WIP | Billed | Write-Off' },
      ],
    },
  ],

  execQuestions: [
    'What is our billable utilisation rate this month and which consultants are below target?',
    'What is our total WIP and how much is at risk of write-off?',
    'What is our realisation rate by service line and where are we losing revenue?',
    'How many debtor days are we carrying and who are the top overdue clients?',
    'Which engagements are unprofitable and what is the root cause?',
    'What is our revenue per consultant trend vs prior year?',
    'How much WIP has been written off this financial year and by which partner?',
    'What is our pipeline value by stage and expected close date?',
    'Which service lines are growing and which are declining in revenue?',
    'What is our average bill rate vs standard rate — where are we discounting?',
    'How does our lock-up (WIP days + debtor days) compare to industry benchmark?',
    'Which clients are most profitable and which should we reprice or exit?',
  ],

  security: {
    rls_required: true,
    roles: [
      { role: 'Partner / Practice Head',     table: 'Dim_ServiceLine', dax: '[PracticeHead_UPN] = USERPRINCIPALNAME()' },
      { role: 'Consultant (Own Data Only)',   table: 'Dim_Employee',    dax: '[UPN] = USERPRINCIPALNAME()' },
      { role: 'Finance / Full Access',        table: 'Dim_ServiceLine', dax: 'USERPRINCIPALNAME() IN VALUES(FinanceUsers[UPN])' },
    ],
    pii_columns: [
      'Dim_Employee[FullName]','Dim_Employee[Email]','Dim_Employee[SalaryBand]',
      'Dim_Client[ContactName]','Dim_Client[ContactEmail]',
    ],
    sensitivity_label: 'Highly Confidential',
    notes: [
      'Individual consultant performance data is confidential — restrict to partner and above.',
      'Client financial data (billing, debtors) restricted to finance and engagement manager.',
      'WIP and write-off data restricted to partners — consultants see own timesheets only.',
      'Pipeline data restricted to partners and BD team.',
    ],
  },

  semanticNotes: [
    'Fact_Timesheets is the primary grain — one row per timesheet line per employee per engagement per day.',
    'Fact_Engagements is a periodic snapshot — use LASTNONBLANK() for current WIP balance.',
    'Fact_Invoices has three date roles: invoice date (active), due date (inactive), paid date (inactive).',
    'Billable Utilisation % uses Fact_ResourceUtilisation for available hours — not raw calendar hours.',
    'WIP Value must reflect standard rates to allow accurate realisation calculation.',
    'Write-off amount lives in Fact_Engagements — not in Fact_Timesheets — to capture partner-level adjustment.',
    'Engagement Margin % = (Revenue − Cost of Labour) ÷ Revenue.',
    'All measures in _Measures table. Folders: Revenue / WIP / Utilisation / Collections / Pipeline / Engagements.',
    'Fiscal year start: July. All TOTALYTD must use "30/06".',
    'Xero Practice Manager is the source of truth for timesheets and WIP. Xero Accounting for invoices and debtors.',
    'HubSpot CRM feeds Fact_Pipeline — sync via scheduled extract or integration.',
    'Revenue Leakage = WIP Value − Invoiced Amount. Track at engagement and service line level.',
  ],

};

/* =============================================================
   PACK_PROPERTY_MANAGEMENT
============================================================= */
'use strict';

const PACK_PROPERTY_MANAGEMENT = {
  code: 'PROPMGMT', icon: '🏢', tier: 1,
  description: 'Residential and commercial property management firms managing rental portfolios on behalf of landlords. Revenue via management fees (% of rent collected). KPIs focus on occupancy, arrears, maintenance, and portfolio growth. Key regulatory obligations include trust accounting and residential tenancy legislation (state-specific).',
  signals: [
    'property management','landlord','tenant','tenancy','rent roll','arrears',
    'vacancy','letting','maintenance','inspection','routine inspection',
    'property manager','disbursement','trust account','lease','bond','portfolio',
    'occupancy','days vacant','propertyme','property tree','console','rest professional',
    'rockend','rent','rental','strata','owner','landlord portal',
  ],
  capabilities: [
    'Portfolio and property management',
    'Tenancy management and renewals',
    'Arrears monitoring and collections',
    'Maintenance request management',
    'Trust account management and disbursements',
    'Routine inspection scheduling and completion',
    'Owner reporting and disbursement statements',
    'Vacancy management and letting',
    'Bond lodgement and management',
    'Lease renewal and expiry tracking',
  ],
  processes: [
    'Property appraisal → listing → tenant application → lease sign → move-in → bond lodgement',
    'Rent due → receipt → trust accounting → arrears follow-up → disbursement to owner',
    'Maintenance request → trade allocation → completion → invoice → owner approval',
    'Routine inspection schedule → inspection → report → owner notification',
    'Lease expiry alert → renewal negotiation → new lease → updated rent',
    'Notice to vacate → bond inspection → claim/refund → re-letting',
  ],
  factTables: [
    {
      name: 'Fact_RentReceipts',
      grain: 'One row = one rent payment transaction per tenancy',
      source: 'Property Management Software (PropertyMe / Console / REST)',
      columns: [
        { name: 'ReceiptKey',    type: 'INT',     desc: 'Surrogate key' },
        { name: 'TenancyKey',    type: 'INT',     desc: 'FK → Dim_Tenancy' },
        { name: 'PropertyKey',   type: 'INT',     desc: 'FK → Dim_Property' },
        { name: 'DateKey',       type: 'INT',     desc: 'FK → Dim_Date (receipt date — active)' },
        { name: 'DueDateKey',    type: 'INT',     desc: 'FK → Dim_Date (due date — inactive)' },
        { name: 'AmountDue',     type: 'DECIMAL', desc: 'Rent amount due' },
        { name: 'AmountPaid',    type: 'DECIMAL', desc: 'Amount received' },
        { name: 'AmountArrears', type: 'DECIMAL', desc: 'Unpaid balance' },
        { name: 'DaysOverdue',   type: 'INT',     desc: 'Days past due date' },
        { name: 'PaymentMethod', type: 'VARCHAR', desc: 'EFT / Cash / BPAY' },
      ],
    },
    {
      name: 'Fact_Vacancies',
      grain: 'One row = one vacant day per property',
      source: 'Property Management Software',
      columns: [
        { name: 'VacancyKey',     type: 'INT',     desc: 'Surrogate key' },
        { name: 'PropertyKey',    type: 'INT',     desc: 'FK → Dim_Property' },
        { name: 'DateKey',        type: 'INT',     desc: 'FK → Dim_Date' },
        { name: 'IsVacant',       type: 'BIT',     desc: 'Vacant on this date' },
        { name: 'DaysVacant',     type: 'INT',     desc: 'Cumulative days vacant' },
        { name: 'WeeklyRentLoss', type: 'DECIMAL', desc: 'Revenue foregone per week' },
      ],
    },
    {
      name: 'Fact_Maintenance',
      grain: 'One row = one maintenance job',
      source: 'Property Management Software',
      columns: [
        { name: 'MaintenanceKey',   type: 'INT',     desc: 'Surrogate key' },
        { name: 'PropertyKey',      type: 'INT',     desc: 'FK → Dim_Property' },
        { name: 'DateKey',          type: 'INT',     desc: 'FK → Dim_Date (raised — active)' },
        { name: 'CompletedDateKey', type: 'INT',     desc: 'FK → Dim_Date (completed — inactive)' },
        { name: 'Category',         type: 'VARCHAR', desc: 'Plumbing / Electrical / General / etc.' },
        { name: 'Priority',         type: 'VARCHAR', desc: 'Emergency / Urgent / Routine' },
        { name: 'Cost',             type: 'DECIMAL', desc: 'Invoice cost' },
        { name: 'DaysToComplete',   type: 'INT',     desc: 'Days from raised to completion' },
        { name: 'IsOpen',           type: 'BIT',     desc: 'Still open flag' },
      ],
    },
    {
      name: 'Fact_ManagementFees',
      grain: 'One row = one fee line per property per month',
      source: 'Trust Accounting System',
      columns: [
        { name: 'FeeKey',        type: 'INT',     desc: 'Surrogate key' },
        { name: 'PropertyKey',   type: 'INT',     desc: 'FK → Dim_Property' },
        { name: 'DateKey',       type: 'INT',     desc: 'FK → Dim_Date (fee month)' },
        { name: 'FeeType',       type: 'VARCHAR', desc: 'Management / Letting / Lease Renewal / Maintenance' },
        { name: 'FeeAmount',     type: 'DECIMAL', desc: 'Fee charged (ex GST)' },
        { name: 'RentCollected', type: 'DECIMAL', desc: 'Rent collected this period' },
        { name: 'FeeRate',       type: 'DECIMAL', desc: 'Management fee % of rent' },
      ],
    },
  ],
  dimensions: [
    { name: 'Dim_Property', type: 'SCD2',     hierarchies: ['State → Suburb → Street → Property'],        key_columns: ['PropertyKey','PropertyID','Address','Suburb','State','Postcode','PropertyType','Bedrooms','WeeklyRentTarget','OwnerKey','ManagerKey','IsActive'] },
    { name: 'Dim_Tenancy',  type: 'SCD2',     hierarchies: ['Property → Tenancy'],                         key_columns: ['TenancyKey','TenantName','LeaseStart','LeaseEnd','WeeklyRent','BondAmount','TenancyStatus','RenewalDate'] },
    { name: 'Dim_Owner',    type: 'Standard', hierarchies: ['Owner → Portfolio'],                          key_columns: ['OwnerKey','OwnerName','ContactEmail','PortfolioSize','ManagementFeeRate'] },
    { name: 'Dim_Employee', type: 'Standard', hierarchies: ['Office → Team → Property Manager'],           key_columns: ['EmployeeKey','FullName','Role','Office','PortfolioCount','IsActive'] },
    { name: 'Dim_Date',     type: 'Standard', hierarchies: ['FiscalYear → Quarter → Month → Week → Day'], key_columns: ['DateKey','Date','Day','Month','Quarter','CalendarYear','FiscalYear','IsWeekend','IsPublicHoliday'] },
  ],
  relationships: [
    { from: 'Fact_RentReceipts[TenancyKey]',      to: 'Dim_Tenancy[TenancyKey]',   cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_RentReceipts[PropertyKey]',     to: 'Dim_Property[PropertyKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_RentReceipts[DateKey]',         to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Receipt date — active' },
    { from: 'Fact_RentReceipts[DueDateKey]',      to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Due date — USERELATIONSHIP()' },
    { from: 'Fact_Vacancies[PropertyKey]',        to: 'Dim_Property[PropertyKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Vacancies[DateKey]',            to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Maintenance[PropertyKey]',      to: 'Dim_Property[PropertyKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_Maintenance[DateKey]',          to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: true,  notes: 'Raised date — active' },
    { from: 'Fact_Maintenance[CompletedDateKey]', to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: false, notes: 'Completed — USERELATIONSHIP()' },
    { from: 'Fact_ManagementFees[PropertyKey]',   to: 'Dim_Property[PropertyKey]', cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
    { from: 'Fact_ManagementFees[DateKey]',       to: 'Dim_Date[DateKey]',          cardinality: 'Many:One', direction: 'Single', active: true,  notes: '' },
  ],
  measures: [
    { name: 'Total Management Fees', folder: 'Revenue / Base',       format: '$#,##0',  dax: `Total Management Fees = SUM(Fact_ManagementFees[FeeAmount])`,                                                                                                    desc: 'Total management fee revenue' },
    { name: 'Rent Collected',        folder: 'Revenue / Base',       format: '$#,##0',  dax: `Rent Collected = SUM(Fact_RentReceipts[AmountPaid])`,                                                                                                            desc: 'Total rent received from tenants' },
    { name: 'Arrears Value',         folder: 'Arrears / Base',       format: '$#,##0',  dax: `Arrears Value = SUM(Fact_RentReceipts[AmountArrears])`,                                                                                                          desc: 'Total unpaid rent in arrears' },
    { name: 'Arrears Rate %',        folder: 'Arrears / Ratios',     format: '0.0%',    dax: `Arrears Rate % = DIVIDE([Arrears Value], [Rent Collected] + [Arrears Value], 0)`,                                                                                desc: 'Arrears as % of total rent due' },
    { name: 'Occupancy Rate %',      folder: 'Portfolio / Ratios',   format: '0.0%',    dax: `Occupancy Rate % =\nDIVIDE(\n    CALCULATE(DISTINCTCOUNT(Fact_Vacancies[PropertyKey]), Fact_Vacancies[IsVacant] = FALSE()),\n    DISTINCTCOUNT(Fact_Vacancies[PropertyKey]), 0\n)`, desc: 'Occupied properties as % of total' },
    { name: 'Vacancy Rate %',        folder: 'Portfolio / Ratios',   format: '0.0%',    dax: `Vacancy Rate % = 1 - [Occupancy Rate %]`,                                                                                                                        desc: 'Vacant properties as % of portfolio' },
    { name: 'Avg Days Vacant',       folder: 'Portfolio / Ratios',   format: '#,##0.0', dax: `Avg Days Vacant = AVERAGE(Fact_Vacancies[DaysVacant])`,                                                                                                          desc: 'Average vacant days per vacant property' },
    { name: 'Maintenance Jobs Open', folder: 'Maintenance / Base',   format: '#,##0',   dax: `Maintenance Jobs Open = CALCULATE(COUNTROWS(Fact_Maintenance), Fact_Maintenance[IsOpen] = TRUE())`,                                                              desc: 'Open maintenance requests' },
    { name: 'Avg Maintenance Cost',  folder: 'Maintenance / Ratios', format: '$#,##0',  dax: `Avg Maintenance Cost = DIVIDE(SUM(Fact_Maintenance[Cost]), COUNTROWS(Fact_Maintenance), 0)`,                                                                     desc: 'Average cost per maintenance job' },
    { name: 'Portfolio Size',        folder: 'Portfolio / Base',     format: '#,##0',   dax: `Portfolio Size = DISTINCTCOUNT(Fact_ManagementFees[PropertyKey])`,                                                                                               desc: 'Total managed properties' },
    { name: 'Revenue YTD',           folder: 'Revenue / Time Intel', format: '$#,##0',  dax: `Revenue YTD = TOTALYTD([Total Management Fees], Dim_Date[Date], "30/06")`,                                                                                       desc: 'Cumulative fee revenue from 1 July' },
    { name: 'Revenue PY',            folder: 'Revenue / Time Intel', format: '$#,##0',  dax: `Revenue PY = CALCULATE([Total Management Fees], SAMEPERIODLASTYEAR(Dim_Date[Date]))`,                                                                            desc: 'Fee revenue same period prior year' },
  ],
  kpis: [
    { name: 'Occupancy Rate',     measure: 'Occupancy Rate %',      target: '> 97%',       good: '> 97%',       warn: '93–97%', critical: '< 93%',    owner: 'Principal / Office Manager',   cadence: 'Weekly'  },
    { name: 'Arrears Rate',       measure: 'Arrears Rate %',        target: '< 3%',        good: '< 3%',        warn: '3–5%',   critical: '> 5%',     owner: 'Property Manager',             cadence: 'Weekly'  },
    { name: 'Days Vacant',        measure: 'Avg Days Vacant',       target: '< 14 days',   good: '< 14 days',   warn: '14–21',  critical: '> 21',     owner: 'Property Manager / Principal', cadence: 'Weekly'  },
    { name: 'Portfolio Growth',   measure: 'Portfolio Size',        target: 'Growth MoM',  good: 'Growing',     warn: 'Flat',   critical: 'Declining', owner: 'Principal / BDM',             cadence: 'Monthly' },
    { name: 'Open Maintenance',   measure: 'Maintenance Jobs Open', target: '< 5% of port',good: '< 5%',        warn: '5–10%',  critical: '> 10%',    owner: 'Property Manager',             cadence: 'Weekly'  },
    { name: 'Management Fee Rev', measure: 'Total Management Fees', target: 'Growth YoY',  good: '>= prior year',warn: 'Flat',  critical: 'Declining', owner: 'Principal / CFO',             cadence: 'Monthly' },
  ],
  pages: [
    { name: 'Executive Summary',     layout: 'Executive',   audience: 'Principal, Director',                      purpose: 'Portfolio health, revenue, occupancy, arrears, and maintenance summary',            slicers: ['Month','Office','Property Manager'],               visuals: [{ type:'Card',title:'Portfolio Size' },{ type:'Card',title:'Occupancy Rate %' },{ type:'Card',title:'Arrears Rate %' },{ type:'Card',title:'Management Fee Revenue' },{ type:'Line',title:'Revenue Trend 12M' },{ type:'Bar',title:'Arrears by Property Manager' }] },
    { name: 'Arrears Management',    layout: 'Operational', audience: 'Property Managers, Principal',              purpose: 'Tenant arrears by age band, property, and property manager',                       slicers: ['Arrears Age Band','Property Manager','Suburb'],   visuals: [{ type:'Bar',title:'Arrears by Days Overdue (7/14/30/60+ days)' },{ type:'Table',title:'Tenants in Arrears — Detail' },{ type:'Card',title:'Total Arrears Value' }] },
    { name: 'Vacancy & Letting',     layout: 'Analytical',  audience: 'Property Managers, BDM',                   purpose: 'Vacant properties, days vacant, letting pipeline',                                  slicers: ['Suburb','Property Manager','Vacancy Status'],     visuals: [{ type:'Table',title:'Vacant Properties — Days Vacant / Weekly Rent Loss' },{ type:'Bar',title:'Days Vacant by Suburb' },{ type:'Card',title:'Total Weekly Rent Lost' }] },
    { name: 'Maintenance Dashboard', layout: 'Operational', audience: 'Property Managers, Maintenance Coordinator',purpose: 'Open jobs, priority, cost, and resolution time',                                   slicers: ['Priority','Category','Property Manager'],         visuals: [{ type:'Table',title:'Open Maintenance Jobs' },{ type:'Bar',title:'Jobs by Category and Priority' },{ type:'Card',title:'Overdue Emergency Jobs' }] },
    { name: 'Owner Portfolio Report',layout: 'Analytical',  audience: 'Property Managers, Principal',              purpose: 'Owner-level portfolio performance — rent, fees, maintenance costs',                 slicers: ['Owner','Property Manager','Month'],               visuals: [{ type:'Matrix',title:'Owner × Property — Rent / Fees / Maintenance' },{ type:'Table',title:'Owners with Arrears or Vacancies' }] },
  ],
  execQuestions: [
    'What is our current portfolio occupancy rate and which properties are vacant?',
    'How much rent is in arrears and which tenants are > 14 days overdue?',
    'How many maintenance jobs are open and how many are overdue?',
    'What is our management fee revenue trend vs prior year?',
    'Which property managers have the highest arrears rates in their portfolios?',
    'How many properties have leases expiring in the next 60 days?',
    'What is our average days vacant and which suburbs are taking longest to let?',
    'Which owners have properties with ongoing maintenance or arrears issues?',
  ],
  security: {
    rls_required: true,
    roles: [
      { role: 'Property Manager',    table: 'Dim_Employee', dax: '[UPN] = USERPRINCIPALNAME()' },
      { role: 'Owner Portal',        table: 'Dim_Owner',    dax: '[OwnerEmail] = USERPRINCIPALNAME()' },
      { role: 'Principal / Finance', table: 'Dim_Employee', dax: 'USERPRINCIPALNAME() IN VALUES(PrincipalUsers[UPN])' },
    ],
    pii_columns: ['Dim_Tenancy[TenantName]','Dim_Owner[ContactEmail]','Dim_Owner[ContactPhone]','Dim_Property[Address]'],
    sensitivity_label: 'Confidential',
    notes: [
      'Trust accounting data is legally restricted — audit trail required.',
      'Tenant PII must not be shared with unauthorised parties.',
      'Owner financial data restricted to principal and assigned property manager.',
    ],
  },
  semanticNotes: [
    'Fact_RentReceipts has two date roles: receipt date (active) and due date (inactive, USERELATIONSHIP()).',
    'Occupancy Rate uses Fact_Vacancies daily snapshot — use LASTNONBLANK() for current occupancy.',
    'Management fee revenue is distinct from rent collected — fee is a % of rent, not the rent itself.',
    'Trust accounting reconciliation must be done externally — this model tracks management performance only.',
    'Tenancy SCD2 required — lease terms and rent amounts change over time.',
    'Arrears rate target varies by state legislation — confirm with principal before setting thresholds.',
  ],
};
