// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioTechBI.AgentHostInfrastructure.Data;

#nullable disable

namespace StudioTechBI.AgentHostInfrastructure.Migrations
{
    [DbContext(typeof(AgentHostDbContext))]
    partial class AgentHostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.Plan", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<int>("CreditsPerCycle").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsUnlimited").HasColumnType("bit");
                b.Property<int>("MaximumConcurrentRequests").HasColumnType("int");
                b.Property<int>("MaximumRequestsPerMinute").HasColumnType("int");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("PlanType").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ResetFrequency").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.ToTable("Plans", "agenthost");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<int>("CreditsRemaining").HasColumnType("int");
                b.Property<int>("CreditsUsedThisCycle").HasColumnType("int");
                b.Property<DateTimeOffset>("CurrentCycleStart").HasColumnType("datetimeoffset");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTimeOffset?>("NextResetDate").HasColumnType("datetimeoffset");
                b.Property<Guid>("PlanId").HasColumnType("uniqueidentifier");
                b.Property<string>("TenantId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("TenantName").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");
                b.HasKey("Id");
                b.HasIndex("TenantId").IsUnique();
                b.HasIndex("PlanId");
                b.ToTable("TenantSubscriptions", "agenthost");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.UsageRecord", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid?>("BlueprintId").HasColumnType("uniqueidentifier");
                b.Property<int>("CreditsConsumed").HasColumnType("int");
                b.Property<string?>("ErrorMessage").HasColumnType("nvarchar(max)");
                b.Property<long>("ExecutionTimeMs").HasColumnType("bigint");
                b.Property<string>("Model").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Provider").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<Guid>("RequestId").HasColumnType("uniqueidentifier");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<Guid>("SubscriptionId").HasColumnType("uniqueidentifier");
                b.Property<string>("TenantId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTimeOffset>("Timestamp").HasColumnType("datetimeoffset");
                b.Property<int>("TokensUsed").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("Timestamp");
                b.HasIndex("SubscriptionId");
                b.ToTable("UsageRecords", "agenthost");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.CreditTransaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<int>("Amount").HasColumnType("int");
                b.Property<int>("BalanceAfter").HasColumnType("int");
                b.Property<int>("BalanceBefore").HasColumnType("int");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string?>("ReferenceId").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<Guid>("SubscriptionId").HasColumnType("uniqueidentifier");
                b.Property<string>("TenantId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("TransactionType").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("SubscriptionId");
                b.ToTable("CreditTransactions", "agenthost");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.SubscriptionHistory", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("ChangedBy").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTimeOffset>("ChangedAt").HasColumnType("datetimeoffset");
                b.Property<Guid>("NewPlanId").HasColumnType("uniqueidentifier");
                b.Property<string?>("Notes").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<Guid?>("PreviousPlanId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("SubscriptionId").HasColumnType("uniqueidentifier");
                b.Property<string>("TenantId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("SubscriptionId");
                b.HasIndex("NewPlanId");
                b.HasIndex("PreviousPlanId");
                b.ToTable("SubscriptionHistories", "agenthost");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", b =>
            {
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.Plan", "Plan")
                    .WithMany("Subscriptions")
                    .HasForeignKey("PlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Plan");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.UsageRecord", b =>
            {
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", "Subscription")
                    .WithMany("UsageRecords")
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Subscription");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.CreditTransaction", b =>
            {
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", "Subscription")
                    .WithMany("CreditTransactions")
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Subscription");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.SubscriptionHistory", b =>
            {
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("NewPlanId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.Plan", null)
                    .WithMany()
                    .HasForeignKey("PreviousPlanId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.HasOne("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", "Subscription")
                    .WithMany("History")
                    .HasForeignKey("SubscriptionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Subscription");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.Plan", b =>
            {
                b.Navigation("Subscriptions");
            });

            modelBuilder.Entity("StudioTechBI.AgentHostDomain.Entities.TenantSubscription", b =>
            {
                b.Navigation("CreditTransactions");
                b.Navigation("History");
                b.Navigation("UsageRecords");
            });
#pragma warning restore 612, 618
        }
    }
}
